name: Main workflow
on: 
  push:
    branches:
      - master
      - v0.1.0-beta
  pull_request:
    branches:
      - master
      - v0.1.0-beta
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: henryliang3027/note@d89be42
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle